Ext.Require("Client/Tabs/MouseoverTab.lua")
Ext.Require("Client/Tabs/EntityTab.lua")
Ext.Require("Client/Tabs/VisualBankTab.lua")
Ext.Require("Client/Tabs/TreeTest.lua")
Ext.Require("Client/ClientUtils.lua")
Ext.Require("Client/Scribe.lua")